<?php

/**
 * Content Taxonomy Configuration
 * * Bu dosya uygulamanın içerik iskeletini, sınıflandırma mantığını
 * ve meta veri standartlarını tanımlar.
 */

return [
    'category' => [
        ['name' => 'Roman'],
        ['name' => 'Öykü'],
        ['name' => 'Şiir'],
        ['name' => 'Deneme'],
        ['name' => 'Biyografi'],
        ['name' => 'Otobiyografi'],
        ['name' => 'Anlatı'],
        ['name' => 'Araştırma'],
        ['name' => 'Mektup'],
        ['name' => 'Günlük'],
        ['name' => 'Tiyatro / Oyun'],
        ['name' => 'Anı'],
        ['name' => 'Gezi Yazısı'],
        ['name' => 'Grafik Roman'],
        ['name' => 'Söyleşi / Röportaj'],
        ['name' => 'Aforizma'],
        ['name' => 'Masal / Fabl'],
        ['name' => 'Manifesto'],
        ['name' => 'Çocuk Kitabı'],
    ],
    'genres' => [
        ['name' => 'Felsefe'],
        ['name' => 'Psikoloji'],
        ['name' => 'Tarih'],
        ['name' => 'Sosyoloji'],
        ['name' => 'Bilim Kurgu'],
        ['name' => 'Distopya'],
        ['name' => 'Fantastik'],
        ['name' => 'Polisiye / Suç'],
        ['name' => 'Erotik'],
        ['name' => 'Gizem'],
        ['name' => 'Gerilim'],
        ['name' => 'Korku'],
        ['name' => 'Aşk / Romantik'],
        ['name' => 'Kişisel Gelişim'],
        ['name' => 'Spiritüel / Maneviyat'],
        ['name' => 'Din'],
        ['name' => 'Bilim / Teknoloji'],
        ['name' => 'Siyaset'],
        ['name' => 'Ekonomi'],
        ['name' => 'Macera'],
        ['name' => 'Sanat / Mimari'],
        ['name' => 'Mitoloji'],
        ['name' => 'Mizah / Hiciv'],
        ['name' => 'Dram'],
        ['name' => 'Politik Dram']
    ],
    'collections' => [
        ['name' => 'Dünya Klasikleri'],
        ['name' => 'Modern Klasikler'],
        ['name' => 'Kült Eserler'],
        ['name' => 'Gençlik Edebiyatı'],
        ['name' => 'Ödüllü Kitaplar'],
        ['name' => 'Çok Satanlar'],
        ['name' => 'Yeni Çıkanlar'],
        ['name' => 'Hasan Ali Yücel Klasikleri'],
    ],
    'countries' => [
        ['name' => 'Türk Edebiyatı'],
        ['name' => 'Uzak Doğu Edebiyatı'],
        ['name' => 'Orta Asya Edebiyatı'],
        ['name' => 'İskandinavya Edebiyatı'],
        ['name' => 'Latin Amerika Edebiyatı'],
        ['name' => 'Rusya Edebiyatı'],
        ['name' => 'Avrupa Edebiyatı'],
        ['name' => 'Kuzey Amerika Edebiyatı'],
        ['name' => 'Orta Doğu Edebiyatı']
    ],
    'themes' => [
        ['name' => 'Distopya'],
        ['name' => 'Yolculuk'],
        ['name' => 'Kader / Özgür İrade'],
        ['name' => 'Adalet / İntikam'],
        ['name' => 'Yalnızlık'],
        ['name' => 'Savaş ve Barış'],
        ['name' => 'Doğa / Çevre'],
        ['name' => 'Aşk / Tutku'],
        ['name' => 'Büyümek / Olgunlaşmak'],
        ['name' => 'Sırlar / Gizemler'],
        ['name' => 'Güç ve Yozlaşma'],
        ['name' => 'Gurbet / Aidiyet'],
        ['name' => 'Zaman Yolculuğu'],
        ['name' => 'Yapay Zeka / Teknoloji'],
        ['name' => 'Erotik'],
    ],
    'moods' => [
        ['name' => 'Karamsar'],
        ['name' => 'İlham Verici'],
        ['name' => 'Gerilimli'],
        ['name' => 'Hüzünlü'],
        ['name' => 'Eğlenceli'],
        ['name' => 'Düşündürücü'],
        ['name' => 'Sürükleyici'],
        ['name' => 'Sakinleştirici'],
        ['name' => 'Sarsıcı'],
        ['name' => 'Nostaljik'],
        ['name' => 'Ürkütücü'],
        ['name' => 'Romantik'],
        ['name' => 'Otantik'],
    ],
];
